### ISSUE TITLE
Launcher Chrome not found. Not installed?

### ISSUE THREAD

**Issue by dbinetti** [heroku/heroku-buildpack-ember-cli#24]
Is this supposed to come from the build pack?  not sure...

```
-----> Running test command `ember t`...
Could not start watchman
Visit https://ember-cli.com/user-guide/#watchman for more info.
Building
.cleaning up
cleaning up...
Built project successfully. Stored in "/app/tmp/class-tests_dist-EwtqnhT2.tmp".
not ok 1 Error
    ---
        message: >
            Launcher Chrome not found. Not installed?
    ...
1..1
# tests 1
# pass  0
# skip  0
# fail  1
Launcher Chrome not found. Not installed?
=================================================================================
ENV Summary:
  TIME: Thu Mar 08 2018 06:39:49 GMT+0000 (UTC)
  TITLE: ember
  ARGV:
  - /app/.heroku/node/bin/node
  - /app/node_modules/.bin/ember
  - t
  EXEC_PATH: /app/.heroku/node/bin/node
  TMPDIR: /tmp
  SHELL: /bin/bash
  PATH:
  - /app/.heroku/node/bin
  - /app/.heroku/yarn/bin
  - /usr/local/bin
  - /usr/bin
  - /bin
  - /app/.sprettur/bin/
  - /app/bin
  - /app/node_modules/.bin
  - /app/.sprettur/bin/
  PLATFORM: linux x64
  FREEMEM: 216121344
  TOTALMEM: 3945816064
  UPTIME: 655959
  LOADAVG: 3.2802734375,2.736328125,2.2998046875
  CPUS:
  - Intel(R) Xeon(R) CPU E5-2680 v2 @ 2.80GHz - 2800
  - Intel(R) Xeon(R) CPU E5-2680 v2 @ 2.80GHz - 2800
  ENDIANNESS: LE
  VERSIONS:
  - ares: 1.13.0
  - cldr: 32.0.1
  - http_parser: 2.7.0
  - icu: 60.2
  - modules: 59
  - napi: 2
  - nghttp2: 1.29.0
  - node: 9.7.1
  - openssl: 1.0.2n
  - tz: 2017c
  - unicode: 10.0
  - uv: 1.19.2
  - v8: 6.2.414.46-node.20
  - zlib: 1.2.11
ERROR Summary:
  - broccoliBuilderErrorStack: [undefined]
  - codeFrame: [undefined]
  - errorMessage: Launcher Chrome not found. Not installed?
  - errorType: [undefined]
  - location:
    - column: [undefined]
    - file: [undefined]
    - line: [undefined]
  - message: Launcher Chrome not found. Not installed?
  - name: Error
  - nodeAnnotation: [undefined]
  - nodeName: [undefined]
  - originalErrorMessage: [undefined]
  - stack: Error: Launcher Chrome not found. Not installed?
    at /app/node_modules/testem/lib/config.js:340:15
    at Array.forEach (<anonymous>)
    at Config.getWantedLaunchers (/app/node_modules/testem/lib/config.js:334:10)
    at /app/node_modules/testem/lib/config.js:304:10
    at /app/node_modules/testem/lib/config.js:293:5
    at tryCatcher (/app/node_modules/bluebird/js/release/util.js:16:23)
    at Promise.successAdapter [as _fulfillmentHandler0] (/app/node_modules/bluebird/js/release/nodeify.js:23:30)
    at Promise._settlePromise (/app/node_modules/bluebird/js/release/promise.js:566:21)
    at Promise._settlePromise0 (/app/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/app/node_modules/bluebird/js/release/promise.js:693:18)
    at Promise._fulfill (/app/node_modules/bluebird/js/release/promise.js:638:18)
    at MappingPromiseArray.PromiseArray._resolve (/app/node_modules/bluebird/js/release/promise_array.js:126:19)
    at MappingPromiseArray._filter (/app/node_modules/bluebird/js/release/map.js:127:10)
    at MappingPromiseArray._promiseFulfilled (/app/node_modules/bluebird/js/release/map.js:99:18)
    at Promise._settlePromise (/app/node_modules/bluebird/js/release/promise.js:574:26)
    at Promise._settlePromise0 (/app/node_modules/bluebird/js/release/promise.js:614:10)
=================================================================================
-----> test command `ember t` failed with exit status 1
```

**Comment by Dhaulagiri** [comment]
Is this error happening locally?  If so that is outside what this buildpack is supporting.

**Comment by dbinetti** [comment]
No, I can run `ember t` without issue.

**Comment by Dhaulagiri** [comment]
@dbinetti I should have been more clear in my original message that regardless this buildpack doesn't bring in headless chrome for you.  I'm not sure where you are running your tests but there is a [headless chrome](https://github.com/heroku/heroku-buildpack-google-chrome) buildpack as well

**Comment by caseywatts** [comment]
@Dhaulagiri let's add that to the ember buildpack readme? :)

**Comment by Dhaulagiri** [comment]
We can but I'm curious the use case here as this is largely dependent on where you are running your tests

**Comment by dbinetti** [comment]
I should have been clearer in my original report.  

The use case is Heroku CI.  I'm trying to get the tests to run, automatically, using the Heroku CI before they deploy to Heroku proper.  This worked using the "Meta" https://github.com/heroku/heroku-buildpack-emberjs pack but isn't on this one.

I'm a novice user, so I'm not even sure if this is expected behavior...

**Comment by Dhaulagiri** [comment]
@dbinetti not a problem at all, hopefully we can help get your situation sorted out.  Do you have your test environment setup using [these instructions](https://devcenter.heroku.com/articles/heroku-ci-browser-and-user-acceptance-testing-uat#google-chrome-via-headless)?

**Comment by dbinetti** [comment]
Perfect!  Problem solved.

Just curious -- is this a new requirement?  It's been a while since I set up the CI but I honestly don't recall having to load this separately.  

In any case, working and happy.  thanks.

**Comment by Dhaulagiri** [comment]
@dbinetti from what I can recall we've always had to do it this way for our CI setups to work properly, so I'm not quite sure how it would have been working for you previously.  I'm happy to poke around a bit more if you want otherwise I'm glad this is working for you!

**Comment by dbinetti** [comment]
no, no need.  works and docs are clear.  just curious.
